[package]
name = "crdts"
description = "Practical serializable thoroughly tested CRDTs (ORSWOT, counters, LWW) ported from riak_dt"
version = "4.0.0"
authors = ["Tyler Neely <t@jujit.su>", "David Rusu <davidrusu.me@gmail.com>"]
license = "Apache-2.0"
homepage = "https://github.com/rust-crdt/rust-crdt"
repository = "https://github.com/rust-crdt/rust-crdt"
documentation = "https://docs.rs/crdts"
keywords = ["crdt", "data-structures", "distributed-systems", "vector-clock", "riak"]
edition = "2018"

[[test]]
name = "test"
path = "test/test.rs"

[dependencies]
num-bigint = "0.2.1"
serde = { version = "1.0", features = ["derive"] }
rand = "0.7"
bitvec = "0.17"
quickcheck = "0.9"

[dev-dependencies]
quickcheck_macros = "0.9"
derive_more = "*"

[profile.release]
debug = true
